package eu.kanade.tachiyomi.util.storage

import android.content.Context
import com.hippo.unifile.UniFile
import tachiyomi.core.common.storage.extension
import tachiyomi.core.common.util.lang.withIOContext
import tachiyomi.core.common.util.system.logcat
import tachiyomi.domain.storage.service.StorageManager
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get

/**
 * Copies user-picked files into the local manga/anime source directory so entries can be added from
 * within the app instead of a file manager. Each picked file becomes one chapter/episode inside a
 * folder named after the entry title (the local source parses chapter/episode numbers from the
 * filenames). Covers/metadata are generated by the local source itself on first scan.
 */
class LocalSourceImporter(
    private val context: Context,
    private val storageManager: StorageManager = Injekt.get(),
) {

    /** Copies [sources] into `<local(anime)>/<title>/`, returning how many succeeded. */
    suspend fun import(isAnime: Boolean, title: String, sources: List<UniFile>): ImportResult = withIOContext {
        val cleanTitle = title.trim()
        if (cleanTitle.isEmpty()) return@withIOContext ImportResult.EmptyTitle
        if (sources.isEmpty()) return@withIOContext ImportResult.NoFiles

        val baseDir = if (isAnime) {
            storageManager.getLocalAnimeSourceDirectory()
        } else {
            storageManager.getLocalMangaSourceDirectory()
        } ?: return@withIOContext ImportResult.NoStorage

        val folderName = DiskUtil.buildValidFilename(cleanTitle)
        val entryDir = baseDir.findFile(folderName)?.takeIf { it.isDirectory }
            ?: baseDir.createDirectory(folderName)
            ?: return@withIOContext ImportResult.NoStorage

        var copied = 0
        var failed = 0
        for (source in sources) {
            val name = source.name
            if (name == null) {
                failed++
                continue
            }
            try {
                val target = entryDir.findFile(name) ?: entryDir.createFile(name)
                if (target == null) {
                    failed++
                    continue
                }
                source.openInputStream().use { input ->
                    target.openOutputStream().use { output -> input.copyTo(output) }
                }
                copied++
            } catch (e: Exception) {
                logcat(throwable = e) { "Failed to import ${source.name} into $folderName" }
                failed++
            }
        }

        if (copied > 0) DiskUtil.createNoMediaFile(entryDir, context)
        ImportResult.Done(title = cleanTitle, copied = copied, failed = failed)
    }

    companion object {
        /** Video containers the player (mpv) can handle. */
        val ANIME_EXTENSIONS = setOf("avi", "flv", "mkv", "mov", "mp4", "webm", "wmv")

        // Archive containers the manga reader can handle. Note: `.epub` is intentionally excluded —
        // the local manga source renders chapters as images, so a text-novel epub (the common case)
        // imports but can't be read. Proper novel support would be a separate feature.
        val MANGA_EXTENSIONS = setOf("zip", "cbz", "rar", "cbr", "7z", "cb7", "tar", "cbt")

        fun supportedExtensions(isAnime: Boolean) = if (isAnime) ANIME_EXTENSIONS else MANGA_EXTENSIONS

        /** MIME filter for the system file picker. */
        fun mimeTypes(isAnime: Boolean): Array<String> = if (isAnime) arrayOf("video/*") else arrayOf("*/*")

        /** Keeps only files with a supported extension. */
        fun filterSupported(files: List<UniFile>, isAnime: Boolean): List<UniFile> {
            val allowed = supportedExtensions(isAnime)
            return files.filter { it.isFile && it.extension?.lowercase() in allowed }
        }
    }
}

sealed interface ImportResult {
    data object EmptyTitle : ImportResult
    data object NoFiles : ImportResult
    data object NoStorage : ImportResult
    data class Done(val title: String, val copied: Int, val failed: Int) : ImportResult
}
